services:
  backend:
    build: 
      context: ./backend
    container_name: eduresume-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      NODE_ENV: development
      PORT: 5000
    networks:
      - eduresume-network

  frontend:
    build:
      context: ./frontend
    container_name: eduresume-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:5000/api
    depends_on:
      - backend
    networks:
      - eduresume-network

networks:
  eduresume-network:
    driver: bridge
